### ISSUE TITLE
Linux packages?

### ISSUE THREAD

**Issue by karezza** [zrax/gsshvnc#3]
Were you planning to create/maintain packages for distributions, such as CentOS?

**Comment by zrax** [comment]
There's an AUR package for Arch Linux (https://aur.archlinux.org/packages/gsshvnc/), but I haven't looked into creating a .spec file or debian build files for other Linux OSes yet...

**Comment by karezza** [comment]
Ok

**Comment by zrax** [comment]
I added a few extra packages for 0.94.  I wasn't able to get it to build for CentOS 6/7 though due to an old compiler and cmake version.
